---
- name: "Create General {{ item.groups }} role"
  tags: configroles
  uri:
    url: "{{ elasticsearch.url }}/_security/role/{{ item.id }}-role"
    method: POST
    user: "{{ secret.elasticsearch.username }}"
    password: "{{ secret.elasticsearch.password }}"
    return_content: yes
    body: "{{ lookup('template','../templates/team_roles.json.j2') }}"
    body_format: json
    force_basic_auth: yes
    status_code: 200,201
    validate_certs: no
  when: item.roles is not defined
  register: response
  changed_when: response.json.role.created == false

- name: polulate created roles into vars
  tags: configroles
  set_fact:
    custom_role: 
      - "{{ item.id }}-role"
  when: item.roles is not defined

- name: "Mapping {{ item.groups }} role for Gsuite Groups"
  tags: configroles
  uri:
    url: "{{ elasticsearch.url }}/_security/role_mapping/{{ item.id }}-mapping"
    method: POST
    user: "{{ secret.elasticsearch.username }}"
    password: "{{ secret.elasticsearch.password }}"
    return_content: yes
    body: "{{ lookup('template','../templates/role_mapping.json.j2') }}"
    body_format: json
    status_code: 200,201
    validate_certs: no
    force_basic_auth: yes
  register: response
  changed_when: response.json.role_mapping.created == false
