---
- name: Create or Update Index Lifecycle Management Policy
  tags: configilm
  uri:
    url: "{{ elasticsearch.url }}/_ilm/policy/{{ item.name }}"
    method: PUT
    user: "{{ secret.elasticsearch.username }}"
    password: "{{ secret.elasticsearch.password }}"
    return_content: yes
    body: "{{ lookup('template', '../templates/ilm_policy.json.j2')  }}"
    body_format: json
    force_basic_auth: yes
    status_code: 200,201
    valuidate_certs: no
  