- name: Add index template
  tags: configindices
  uri:
    url: "https://{{ elasticsearch.host }}:{{ elasticsearch.port }}/_template/{{item}}_index_template"
    method: PUT
    user: "{{ elasticsearch.username }}"
    password: "{{ elasticsearch.password }}"
    return_content: yes
    body: "{{ lookup('file','../files/{{ item }}_index_template.json') }}"
    body_format: json
    status_code: 200,201
    validate_certs: no
    force_basic_auth: yes
  register: response
  changed_when: response.status == 201
  with_items:
    - hooq-app
    - hooq-nightly-app-playgo-logs