version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "nikita_db"
    ports:
      - "54320:5432"
    volumes:
      - nikita_db_data:/var/lib/postgresql/data
    networks:
      - nikita_net
    restart: always
volumes:
  nikita_db_data:
networks:
  nikita_net:
    driver: bridge
