#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "required 2 arguments: PRIVATE_SSH_KEY PUBLIC_SSH_KEY"
  exit 1
fi

PRIVATE_SSH_KEY="$1"
PUBLIC_SSH_KEY="$2"

mkdir ~/.ssh
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts;
echo $PRIVATE_SSH_KEY > ~/.ssh/id_rsa
echo $PUBLIC_SSH_KEY > ~/.ssh/id_rsa.pub
chmod -R 600 ~/.ssh/id_rsa
chmod -R 600 ~/.ssh/id_rsa.pub
eval $(ssh-agent)
