- name: Add visualizations to Kibana
  uri:
    url: "{{ elasticsearch.url }}/.kibana/_doc/visualization:{{item}}"
    method: POST
    user: "{{ secret.elasticsearch.username }}"
    password: "{{ secret.elasticsearch.password }}"
    body: "{{ lookup('template','../templates/visualization/containers/{{item}}.json') }}"
    body_format: json
    status_code: 201,200
    validate_certs: no
  with_items:
   - docker_containers
   - docker_number_of_containers
   - docker_containers_per_host
   - docker_images_names
   - docker_cpu_usage
   - docker_memory_usage
   - docker_network_io
  register: response
  changed_when: response.status == 201
