- name: Add search to Kibana
  uri:
    url: "{{ elasticsearch.url }}/.kibana/_doc/search:{{item}}"
    method: POST
    user: "{{ secret.elasticsearch.username }}"
    password: "{{ secret.elasticsearch.password }}"
    body: "{{ lookup('template','../templates/search/{{item}}.json') }}"
    body_format: json
    status_code: 201,200
    validate_certs: no
  with_items:
    - metricbeat-docker-ecs
  register: response
  changed_when: response.status == 201
