--- # ansible-playbook playbook.yml -vv --vault-password-file ~/.vault_pass.txt --tags functionbeat(or)configroles(or)configindices
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Include HOOQ-ELASTIC hosts vars
      tags:
        - HOOQ-ELASTIC
      include_vars:
        dir: vars/hosts
        extensions:
          - yml
          - yaml
        files_matching: HOOQ-ELASTIC*
      no_log: true
    - name: Include hooq-elastic-stack hosts vars
      tags:
        - hooq-elastic-stack
      include_vars:
        dir: vars/hosts
        extensions:
          - yml
          - yaml
        files_matching: hooq-elastic-stack*
      no_log: true
    - name: Include spaces vars
      tags:
        - configspaces
      include_vars:
        dir: vars/spaces
    - name: Run config kibana spaces
      tags:
        - configspaces
      include_role:
        name: configspaces
      loop: "{{ kibana_spaces|flatten(levels=1) }}"
      loop_control:
        loop_var: item
    - name: include roles vars
      tags: configroles
      include_vars:
        dir: vars/roles
    - name: debug esroles
      tags: configroles
      debug:
        var: esroles
    - name: Run configroles
      tags: configroles
      include_role:
        name: configroles
      loop: "{{ esroles|flatten(levels=1) }}"
      loop_control:
        loop_var: item
    - name: include ilm vars
      tags: configilm
      include_vars:
        dir: vars/ilm
    - name: Run configilm
      tags: configilm
      include_role:
        name: configilm
      loop: "{{ ilm_policies|flatten(levels=1) }}"
      loop_control:
        loop_var: item

- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: include host vars
      tags: functionbeat
      include_vars:
        dir: vars/hosts
        files_matching: hooq-elastic-stack*
    - name: find all config
      tags: functionbeat
      find:
        path: "vars/functionbeat/{{ lookup('env', 'FUNCTIONBEAT_TEAM') }}"
        file_type: file
        patterns: "*.yml"
      register: files_matched
    - name: run functionbeat deployment
      tags: functionbeat
      include_role:
        name: functionbeat
      loop: "{{ files_matched.files|flatten(levels=1) }}"

- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Run configindices
      tags: configindices
      include_role:
        name: configindices
