name: anubis-stop-all-tasks
on:
  repository_dispatch:
    types: [anubis-stop-all-tasks-dev]

jobs:
  anubis-stop-all-tasks-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: run anubis test execution
        run: for i in `aws ecs list-tasks --region ap-southeast-1 --cluster anubis-dev | jq .taskArns  | awk -F"/" '{print $2}' | tr -d "\"\,"`; do aws ecs stop-task --region ap-southeast-1 --cluster anubis-dev --task $i; done
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_ANUBIS: ${{ secrets.TF_TOKEN_ANUBIS }}