name: api-test-execution-dev
on:
  repository_dispatch:
    types: [api-dev]

jobs:
  anubis-test-execution-job-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: run anubis test execution
        run: aws ecs run-task --region ap-southeast-1 --cluster anubis-dev  --task-definition anubis_dev-api-td
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_ANUBIS: ${{ secrets.TF_TOKEN_ANUBIS }}


