name: anubis-code-deploy-stag
on:
  push:
    tags:
      - anubis-code-stag-*

jobs:
  anubis-image-build-job-stag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: login to our private repository
        run: docker login docker.pkg.github.com --username techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.TECHACC_TOKEN }}

      - name: dockerize the application
        run: export APP_TAG=`git rev-parse HEAD | cut -c1-7` && docker build -t docker.pkg.github.com/hooqtv/monohooq/anubis:$APP_TAG .
        working-directory: anubis/src

      - name: push image to our Private Hub
        run: export APP_TAG=`git rev-parse HEAD | cut -c1-7` && docker push docker.pkg.github.com/hooqtv/monohooq/anubis:$APP_TAG
        working-directory: anubis/src


  anubis-ecs-deployment-stag:
    runs-on: ubuntu-latest
    needs: anubis-image-build-job-stag
    steps:
      - name: checkout public repo
        uses: actions/checkout@v1.2.0

      - name: get the latest terraform version
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_STABLE_VERSION"/terraform_"$TF_STABLE_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_STABLE_VERSION:  ${{ secrets.TF_STABLE_VERSION }}

      - name: add GitHub Sha as version to terraform
        run: export GITHUBSHA=`sed -e 's/^"//' -e 's/"$//' <<<"$MASTER_COMMIT_ID" | cut -c1-7` && sed -i -e "s/GITHUBSHA/$GITHUBSHA/g" variables.tf
        working-directory: anubis/code-deploy
        env:
          MASTER_COMMIT_ID: ${{ toJson(github.event.pull_request.merge_commit_sha) }}

      - name: login to our private repository
        run: docker login docker.pkg.github.com --username techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.TECHACC_TOKEN }}

      - name: init and plan terraform anubis deployment stag
        run:  export APP_TAG=`echo $(git rev-parse HEAD) | cut -c1-7` && sed -i -e "s/APP_TAG/$APP_TAG/g" *.tf && sed -i -e "s/TF_TOKEN_ANUBIS/$TF_TOKEN_ANUBIS/g" *.tf && sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf && /usr/bin/terraform init -input=false && /usr/bin/terraform plan -input=false
        working-directory: anubis/code-deploy
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_STAG_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_ANUBIS: ${{ secrets.TF_TOKEN_ANUBIS }}

      - name: apply terraform anubis deployment stag
        run: /usr/bin/terraform apply -input=false -auto-approve
        working-directory: anubis/code-deploy
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_STAG_SECRET_KEY }}

  
             
              