name: anubis-infra-deploy-stag
on:
  push:
    tags:
      - anubis-infra-stag-*

jobs:
  anubis-infra-stag-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_TEST_VERSION"/terraform_"$TF_TEST_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_TEST_VERSION: ${{ secrets.TF_TEST_VERSION }}

      - name: Add GitHub Sha as version to terraform
        run: export GITHUBSHA=`git rev-parse HEAD | cut -c1-7` && sed -i -e "s/GITHUBSHA/$GITHUBSHA/g" variables.tf
        working-directory: anubis/infra-deploy/

      - name: Init and plan terraform anubis infra stag
        run: |
           sed -i -e "s/TF_TOKEN_ANUBIS/$TF_TOKEN_ANUBIS/g" *.tf
           sed -i -e "s/DESIRED_CAPACITY/$DESIRED_CAPACITY/g" *.tf
           sed -i -e "s/MIN_SIZE/$MIN_SIZE/g" *.tf
           sed -i -e "s/MAX_SIZE/$MAX_SIZE/g" *.tf
           /usr/bin/terraform init -input=false
           /usr/bin/terraform plan -input=false
        working-directory: anubis/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          TF_TOKEN_ANUBIS: ${{ secrets.TF_TOKEN_ANUBIS }}
          MIN_SIZE: 1
          MAX_SIZE: 3
          DESIRED_CAPACITY: 1

      - name: Apply terraform anubis infra stag
        run: |
          sed -i -e "s/TF_TOKEN_ANUBIS/$TF_TOKEN_ANUBIS/g" *.tf
          sed -i -e "s/DESIRED_CAPACITY/$DESIRED_CAPACITY/g" *.tf
          sed -i -e "s/MIN_SIZE/$MIN_SIZE/g" *.tf
          sed -i -e "s/MAX_SIZE/$MAX_SIZE/g" *.tf
          /usr/bin/terraform apply -input=false -auto-approve
        working-directory: anubis/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          MIN_SIZE: 1
          MAX_SIZE: 3
          DESIRED_CAPACITY: 1
