name: anubis-auto-scaling-group-down-stag
on:
  repository_dispatch:
    types: [auto-scale-down-stag]

jobs:
  anubis-auto-scaling-group-down-stag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_STABLE_VERSION"/terraform_"$TF_STABLE_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_STABLE_VERSION:  ${{ secrets.TF_STABLE_VERSION }}

      - name: Add GitHub Sha as version to terraform
        run: export GITHUBSHA=`git rev-parse HEAD | cut -c1-7` && sed -i -e "s/GITHUBSHA/$GITHUBSHA/g" variables.tf
        working-directory: anubis/infra-deploy/

      - name: Init and Plan for auto scale down
        run: |
          sed -i -e "s/TF_TOKEN_ANUBIS/$TF_TOKEN_ANUBIS/g" *.tf
          sed -i -e "s/DESIRED_CAPACITY/$DESIRED_CAPACITY/g" *.tf
          sed -i -e "s/MIN_SIZE/$MIN_SIZE/g" *.tf
          sed -i -e "s/MAX_SIZE/$MAX_SIZE/g" *.tf
          /usr/bin/terraform init -input=false
          /usr/bin/terraform plan -input=false
        working-directory: anubis/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          TF_TOKEN_ANUBIS: ${{ secrets.TF_TOKEN_ANUBIS }}
          MIN_SIZE: 0
          MAX_SIZE: 0
          DESIRED_CAPACITY: 0

      - name: Apply terraform for auto scale down
        run: |
          sed -i -e "s/TF_TOKEN_ANUBIS/$TF_TOKEN_ANUBIS/g" *.tf
          sed -i -e "s/DESIRED_CAPACITY/$DESIRED_CAPACITY/g" *.tf
          sed -i -e "s/MIN_SIZE/$MIN_SIZE/g" *.tf
          sed -i -e "s/MAX_SIZE/$MAX_SIZE/g" *.tf
          /usr/bin/terraform apply -input=false -auto-approve
        working-directory: anubis/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          MIN_SIZE: 0
          MAX_SIZE: 0
          DESIRED_CAPACITY: 0