name: build-custom-metricbeat
on:
  push:
    tags:
      - metricbeat-custom-*
    paths:
      - 'cloud_sre/Ops_Collection/metricbeat_config/*'

jobs:
  metricbeat-custom-config-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: login to our private repository
        run: docker login quay.io --username hooq+techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - name: Docker build and push custom metricbeat image
        run: docker build -t "quay.io/hooq/metricbeat:${METRICBEAT_VERSION}" --build-arg METRICBEAT_VERSION="${METRICBEAT_VERSION}" . && docker push "quay.io/hooq/metricbeat:${METRICBEAT_VERSION}"
        working-directory: cloud_sre/Ops_Collection/metricbeat_config/
        env:
          METRICBEAT_VERSION: "7.5.2"
