name: cloud-sre-aws-generic
on:
 push:
  tags:
    - hooq-generic-resources-v*
  paths:
    - 'cloud_sre/aws/generic/**.tf'
jobs:
  deploy-cloud-sre-aws-generic:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@master
        
      - name : Get the latest terraform version
        run: make terraform-install
          
      - name: Init and plan create S3 bucket for ALB access logs for AWS PROD
        run: sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" backend.tf &&  /usr/bin/terraform init -input=false  && /usr/bin/terraform plan -input=false
        working-directory: cloud_sre/aws/generic/
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PROD_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}

      - name: Apply create S3 bucket for ALB access logs for AWS PROD
        run:  /usr/bin/terraform apply -input=false -auto-approve
        working-directory: cloud_sre/aws/generic/
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PROD_SECRET_KEY }}