name: cloud-sre-aws-get-github-secrets
on:
  push:
    tags:
      - hooq-get-github-secrets-v*
    paths:
      - "cloud_sre/miscellaneous/**.tf"
jobs:
  deploy-cloud-sre-aws-get-github-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        # run: wget `echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip"`  && unzip *.zip && sudo mv terraform /usr/bin/terraform
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_STABLE_VERSION"/terraform_"$TF_STABLE_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_STABLE_VERSION: ${{ secrets.TF_STABLE_VERSION }}

      - name: get the secret values
        run: |
          sed -i -e "s@TF_TOKEN_CLOUD_SRE@$TF_TOKEN_CLOUD_SRE@g" backend.tf
          sed -i -e "s@\bTF_TOKEN_CLOUD_SRE\b@$TF_TOKEN_CLOUD_SRE@g" main.tf
          sed -i -e "s@\bANSIBLE_VAULT_PASSWORD\b@$ANSIBLE_VAULT_PASSWORD@g" main.tf
          sed -i -e "s@\bAWS_CC_PROD_ACCESS_KEY\b@$AWS_CC_PROD_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_CC_PROD_SECRET_KEY\b@$AWS_CC_PROD_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_DEFAULT_REGION\b@$AWS_DEFAULT_REGION@g" main.tf
          sed -i -e "s@\bAWS_DEV_ACCESS_KEY\b@$AWS_DEV_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_DEV_SECRET_KEY\b@$AWS_DEV_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_ECR_REPO\b@$AWS_ECR_REPO@g" main.tf
          sed -i -e "s@\bAWS_ECR_URL\b@$AWS_ECR_URL@g" main.tf
          sed -i -e "s@\bDOCKER_TAG_MIYAZAKI_PROD\b@$DOCKER_TAG_MIYAZAKI_PROD@g" main.tf
          sed -i -e "s@\bAWS_PEER_DEV_ACCESS_KEY\b@$AWS_PEER_DEV_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_PEER_DEV_SECRET_KEY\b@$AWS_PEER_DEV_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_PLAY_ACCESS_KEY\b@$AWS_PLAY_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_PLAY_SECRET_KEY\b@$AWS_PLAY_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_PROD_ACCESS_KEY\b@$AWS_PROD_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_PROD_SECRET_KEY\b@$AWS_PROD_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_SRE_ACCESS_KEY\b@$AWS_SRE_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_SRE_SECRET_KEY\b@$AWS_SRE_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_STAG_ACCESS_KEY\b@$AWS_STAG_ACCESS_KEY@g" main.tf
          sed -i -e "s@\bAWS_STAG_SECRET_KEY\b@$AWS_STAG_SECRET_KEY@g" main.tf
          sed -i -e "s@\bAWS_ECR_URL\b@$AWS_ECR_URL@g" main.tf
          sed -i -e "s@\bDB_PASSWORD\b@$DB_PASSWORD@g" main.tf
          DEPLOYER_KEY_PRIV=`echo ${DEPLOYER_KEY_PRIV} | tr '\n' "\\n"` && sed -i -e "s#\bDEPLOYER_KEY_PRIV\b#$DEPLOYER_KEY_PRIV#g" main.tf
          sed -i -e "s|\bDEPLOYER_KEY_PUB\b|$DEPLOYER_KEY_PUB|g" main.tf
          sed -i -e "s@\bDOCKERGITHUBTOKEN\b@$DOCKERGITHUBTOKEN@g" main.tf
          sed -i -e "s@\bELASTIC_CLOUDID\b@$ELASTIC_CLOUDID@g" main.tf
          sed -i -e "s@\bELASTIC_CLOUD_ID\b@$ELASTIC_CLOUD_ID@g" main.tf
          sed -i -e "s@\bELASTIC_CLOUD_VAULT_PASS\b@$ELASTIC_CLOUD_VAULT_PASS@g" main.tf
          sed -i -e "s@\bELASTIC_PASS\b@$ELASTIC_PASS@g" main.tf
          sed -i -e "s@\bELASTIC_PASSWORD\b@$ELASTIC_PASSWORD@g" main.tf
          sed -i -e "s@\bELASTIC_URL\b@$ELASTIC_URL@g" main.tf
          sed -i -e "s@\bELASTIC_USERNAME\b@$ELASTIC_USERNAME@g" main.tf
          sed -i -e "s@\bFUNCTIONBEAT_VERSION\b@$FUNCTIONBEAT_VERSION@g" main.tf
          sed -i -e "s@\bGITHUB_PACKAGE_TOKEN\b@$GITHUB_PACKAGE_TOKEN@g" main.tf
          sed -i -e "s@\bMIYAZAKI_ANSIBLE_VAULT_PASSWORD\b@$MIYAZAKI_ANSIBLE_VAULT_PASSWORD@g" main.tf
          sed -i -e "s@\bMIYAZAKI_DEV_KEY\b@$MIYAZAKI_DEV_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_DEV_NEWRELIC_BROWSER_LICENSE_KEY\b@$MIYAZAKI_DEV_NEWRELIC_BROWSER_LICENSE_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_DEV_NEWRELIC_KEY\b@$MIYAZAKI_DEV_NEWRELIC_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_DEV_REDIS_PASSWORD\b@$MIYAZAKI_DEV_REDIS_PASSWORD@g" main.tf
          sed -i -e "s@\bMIYAZAKI_PLAY_REDIS_PASSWORD\b@$MIYAZAKI_PLAY_REDIS_PASSWORD@g" main.tf
          sed -i -e "s@\bMIYAZAKI_PROD_KEY\b@$MIYAZAKI_PROD_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_PROD_NEWRELIC_BROWSER_LICENSE_KEY\b@$MIYAZAKI_PROD_NEWRELIC_BROWSER_LICENSE_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_PROD_NEWRELIC_KEY\b@$MIYAZAKI_PROD_NEWRELIC_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_PROD_REDIS_PASSWORD\b@$MIYAZAKI_PROD_REDIS_PASSWORD@g" main.tf
          sed -i -e "s@\bMIYAZAKI_STAG_KEY\b@$MIYAZAKI_STAG_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_STAG_NEWRELIC_BROWSER_LICENSE_KEY\b@$MIYAZAKI_STAG_NEWRELIC_BROWSER_LICENSE_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_STAG_NEWRELIC_KEY\b@$MIYAZAKI_STAG_NEWRELIC_KEY@g" main.tf
          sed -i -e "s@\bMIYAZAKI_STAG_REDIS_PASSWORD\b@$MIYAZAKI_STAG_REDIS_PASSWORD@g" main.tf
          sed -i -e "s@\bNIKITA_ANSIBLE_VAULT_PASSWORD\b@$NIKITA_ANSIBLE_VAULT_PASSWORD@g" main.tf
          sed -i -e "s@\bPOC_ELASTIC_CLOUDID\b@$POC_ELASTIC_CLOUDID@g" main.tf
          sed -i -e "s@\bPOC_ELASTIC_PASSWORD\b@$POC_ELASTIC_PASSWORD@g" main.tf
          sed -i -e "s@\bPOC_ELASTIC_URL\b@$POC_ELASTIC_URL@g" main.tf
          sed -i -e "s@\bQUAY_REGISTRY_TOKEN\b@$QUAY_REGISTRY_TOKEN@g" main.tf
          sed -i -e "s@\bQUAY_ACCESS_TOKEN\b@$QUAY_ACCESS_TOKEN@g" main.tf
          sed -i -e "s@\bTECHACC_TOKEN\b@$TECHACC_TOKEN@g" main.tf
          sed -i -e "s@\bTF_NIKITA_POSTGRES_PASSWORD\b@$TF_NIKITA_POSTGRES_PASSWORD@g" main.tf
          sed -i -e "s@\bTF_STABLE_VERSION\b@$TF_STABLE_VERSION@g" main.tf
          sed -i -e "s@\bTF_TEST_VERSION\b@$TF_TEST_VERSION@g" main.tf
          sed -i -e "s@\bTF_TOKEN_ANUBIS\b@$TF_TOKEN_ANUBIS@g" main.tf
          sed -i -e "s@\bTF_TOKEN_DISCOVER\b@$TF_TOKEN_DISCOVER@g" main.tf
          sed -i -e "s@\bTF_TOKEN_MIYAZAKI\b@$TF_TOKEN_MIYAZAKI@g" main.tf
          sed -i -e "s@\bTF_TOKEN_NIKITA\b@$TF_TOKEN_NIKITA@g" main.tf
          sed -i -e "s@\bTF_TOKEN_TEST_SERVICE\b@$TF_TOKEN_TEST_SERVICE@g" main.tf
          /usr/bin/terraform init -input=false
          /usr/bin/terraform plan -input=false
          set +x
        working-directory: cloud_sre/miscellaneous/
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD	}}
          AWS_CC_PROD_ACCESS_KEY: ${{ secrets.AWS_CC_PROD_ACCESS_KEY	}}
          AWS_CC_PROD_SECRET_KEY: ${{ secrets.AWS_CC_PROD_SECRET_KEY	}}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION	}}
          AWS_DEV_ACCESS_KEY: ${{ secrets.AWS_DEV_ACCESS_KEY	}}
          AWS_DEV_SECRET_KEY: ${{ secrets.AWS_DEV_SECRET_KEY	}}
          AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO	}}
          AWS_ECR_URL: ${{ secrets.AWS_ECR_URL	}}
          AWS_PEER_DEV_ACCESS_KEY: ${{ secrets.AWS_PEER_DEV_ACCESS_KEY	}}
          AWS_PEER_DEV_SECRET_KEY: ${{ secrets.AWS_PEER_DEV_SECRET_KEY	}}
          AWS_PLAY_ACCESS_KEY: ${{ secrets.AWS_PLAY_ACCESS_KEY	}}
          AWS_PLAY_SECRET_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY	}}
          AWS_PROD_ACCESS_KEY: ${{ secrets.AWS_PROD_ACCESS_KEY	}}
          AWS_PROD_SECRET_KEY: ${{ secrets.AWS_PROD_SECRET_KEY	}}
          AWS_SRE_ACCESS_KEY: ${{ secrets.AWS_SRE_ACCESS_KEY	}}
          AWS_SRE_SECRET_KEY: ${{ secrets.AWS_SRE_SECRET_KEY	}}
          AWS_STAG_ACCESS_KEY: ${{ secrets.AWS_STAG_ACCESS_KEY	}}
          AWS_STAG_SECRET_KEY: ${{ secrets.AWS_STAG_SECRET_KEY	}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD	}}
          DOCKER_TAG_MIYAZAKI_PROD: ${{ secrets.DOCKER_TAG_MIYAZAKI_PROD }}
          DEPLOYER_KEY_PRIV: ${{ secrets.DEPLOYER_KEY_PRIV	}}
          DEPLOYER_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB	}}
          DOCKERGITHUBTOKEN: ${{ secrets.DOCKERGITHUBTOKEN	}}
          ELASTIC_CLOUDID: ${{ secrets.ELASTIC_CLOUDID	}}
          ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID	}}
          ELASTIC_CLOUD_VAULT_PASS: ${{ secrets.ELASTIC_CLOUD_VAULT_PASS	}}
          ELASTIC_PASS: ${{ secrets.ELASTIC_PASS	}}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD	}}
          ELASTIC_URL: ${{ secrets.ELASTIC_URL	}}
          ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME	}}
          FUNCTIONBEAT_VERSION: ${{ secrets.FUNCTIONBEAT_VERSION	}}
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN	}}
          MIYAZAKI_ANSIBLE_VAULT_PASSWORD: ${{ secrets.MIYAZAKI_ANSIBLE_VAULT_PASSWORD	}}
          MIYAZAKI_DEV_KEY: ${{ secrets.MIYAZAKI_DEV_KEY	}}
          MIYAZAKI_DEV_NEWRELIC_BROWSER_LICENSE_KEY: ${{ secrets.MIYAZAKI_DEV_NEWRELIC_BROWSER_LICENSE_KEY	}}
          MIYAZAKI_DEV_NEWRELIC_KEY: ${{ secrets.MIYAZAKI_DEV_NEWRELIC_KEY	}}
          MIYAZAKI_DEV_REDIS_PASSWORD: ${{ secrets.MIYAZAKI_DEV_REDIS_PASSWORD	}}
          MIYAZAKI_PLAY_REDIS_PASSWORD: ${{ secrets.MIYAZAKI_PLAY_REDIS_PASSWORD	}}
          MIYAZAKI_PROD_KEY: ${{ secrets.MIYAZAKI_PROD_KEY	}}
          MIYAZAKI_PROD_NEWRELIC_BROWSER_LICENSE_KEY: ${{ secrets.MIYAZAKI_PROD_NEWRELIC_BROWSER_LICENSE_KEY	}}
          MIYAZAKI_PROD_NEWRELIC_KEY: ${{ secrets.MIYAZAKI_PROD_NEWRELIC_KEY	}}
          MIYAZAKI_PROD_REDIS_PASSWORD: ${{ secrets.MIYAZAKI_PROD_REDIS_PASSWORD	}}
          MIYAZAKI_STAG_KEY: ${{ secrets.MIYAZAKI_STAG_KEY	}}
          MIYAZAKI_STAG_NEWRELIC_BROWSER_LICENSE_KEY: ${{ secrets.MIYAZAKI_STAG_NEWRELIC_BROWSER_LICENSE_KEY	}}
          MIYAZAKI_STAG_NEWRELIC_KEY: ${{ secrets.MIYAZAKI_STAG_NEWRELIC_KEY	}}
          MIYAZAKI_STAG_REDIS_PASSWORD: ${{ secrets.MIYAZAKI_STAG_REDIS_PASSWORD	}}
          NIKITA_ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD	}}
          POC_ELASTIC_CLOUDID: ${{ secrets.POC_ELASTIC_CLOUDID	}}
          POC_ELASTIC_PASSWORD: ${{ secrets.POC_ELASTIC_PASSWORD	}}
          POC_ELASTIC_URL: ${{ secrets.POC_ELASTIC_URL	}}
          QUAY_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN	}}
          QUAY_ACCESS_TOKEN: ${{ secrets.QUAY_ACCESS_TOKEN	}}
          TECHACC_TOKEN: ${{ secrets.TECHACC_TOKEN	}}
          TF_NIKITA_POSTGRES_PASSWORD: ${{ secrets.TF_NIKITA_POSTGRES_PASSWORD	}}
          TF_STABLE_VERSION: ${{ secrets.TF_STABLE_VERSION	}}
          TF_TEST_VERSION: ${{ secrets.TF_TEST_VERSION	}}
          TF_TOKEN_ANUBIS: ${{ secrets.TF_TOKEN_ANUBIS	}}
          TF_TOKEN_DISCOVER: ${{ secrets.TF_TOKEN_DISCOVER	}}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI	}}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA	}}
          TF_TOKEN_TEST_SERVICE: ${{ secrets.TF_TOKEN_TEST_SERVICE}}

      - name: display the secret values
        run: |
          /usr/bin/terraform apply -input=false -auto-approve
        working-directory: cloud_sre/miscellaneous/
        env:
          TF_IN_AUTOMATION: true
