name: cloudsre-docs-generator
on:
  push:
    branches:
      - CS-*
    tags:
      - cloudsre-docs-generator-*
    paths:
      - 'cloud_sre/docs/**'
jobs:
  deploy-cloudsre-docs-generator:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Run playbook to create S3 bucket in prod
        run: |
          ansible-playbook playbook.yml -vv -e s3_bucket="$S3_BUCKET" --tags="docsgen"
        working-directory: cloud_sre/docs
        env:
          S3_BUCKET: hooq-cloudsre-workbook-docs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: compile docs to HTML
        run: make html
        working-directory: cloud_sre/docs

      - name: Zip up compiled html docs
        run: tar -czf ../../../../../cloud_sre/docs/workbookdocs.tar.gz .
        working-directory: cloud_sre/docs/workbook/_build/html

      - name: Upload html docs to s3
        run: aws s3 cp workbookdocs.tar.gz s3://${BUCKET_NAME}/files/cloudsre/docs/workbookdocs.tar.gz --sse AES256
        working-directory: cloud_sre/docs
        env:
          BUCKET_NAME: hooq-cloudsre-workbook-docs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}