name: cloudsre-hello-world-functionbeat-deploy-play
on:
  push:
    branches:
      - CS-*
    paths:
      - 'services/cloudsre-hello-world-app/functionbeat-deploy/**'

jobs:
  cloudsre-hello-world-functionbeat-play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Install botocore and boto3
        run: pip install botocore && pip install boto3

      - name: functionbeat deploy for the miyazaki dev
        run: make ansible-apply
        working-directory: services/cloudsre-hello-world-app/functionbeat-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: play
          SERVICE: helloworld-app
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          FUNCTIONBEAT_VERSION: 7.5.2
