name: cloudsre-hello-world-app-infra-deploy-play
on:
 push:
   branches:
     - master
   tags:
     - STAG-CLOUDSRE-INFRA-*
   paths:
     - "services/cloudsre-hello-world-app/infra-deploy/*.tf"
     - "!services/cloudsre-hello-world-app/infra-deploy/functionbeat.conf"

jobs:
  cloudsre-hello-world-app-infra-play-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_TEST_VERSION"/terraform_"$TF_TEST_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_TEST_VERSION: ${{ secrets.TF_TEST_VERSION }}

      - name: Add GitHub Sha as version to terraform
        run: export GITHUBSHA=`git rev-parse HEAD | cut -c1-7` && sed -i -e "s/GITHUBSHA/$GITHUBSHA/g" variables.tf
        working-directory: services/cloudsre-hello-world-app/infra-deploy/

      - name: Init and plan terraform cloudsre-hello-world-app infra play
        run: sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf && sed -i -e "s/ELASTIC_CLOUD_ID/$ELASTIC_CLOUD_ID/g" *.tf && sed -i -e "s/ELASTIC_PASSWORD/$ELASTIC_CLOUD_PASS/g" *.tf && sed -i -e "s/DOCKERGITHUBTOKEN/$DOCKER_GITHUB_TOKEN/g" *.tf && sed -i -e "s@AWS_ACCESSKEY@$AWS_ACCESS_KEY_ID@g" *.tf && sed -i -e "s@AWS_SECRETKEY@$AWS_SECRET_ACCESS_KEY@g" *.tf && sed -i -e "s@ELASTIC_URL@$ELASTIC_CLOUD_URL@g" *.tf && /usr/bin/terraform init -input=false && /usr/bin/terraform plan -input=false
        working-directory: services/cloudsre-hello-world-app/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKERGITHUBTOKEN }}
          ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_CLOUDID }}
          ELASTIC_CLOUD_PASS: ${{ secrets.ELASTIC_PASS }}
          ELASTIC_CLOUD_URL: ${{ secrets.ELASTIC_URL }}

      - name: Apply terraform cloudsre-hello-world-app infra play
        run: /usr/bin/terraform apply -input=false -auto-approve
        working-directory: services/cloudsre-hello-world-app/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
