name: delete-terraform-miyazaki-dev-resources
on:
  push:
    tags:
      - delete-miyazaki-dev-*
jobs:
  delete-terraform-miyazaki-dev-resources-job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Destroy metricbeat miyazaki ECS service
        run: make terraform-destroy
        working-directory: services/miyazaki/metrics-deploy/metricbeat/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}

      - name: Destroy terraform miyazaki code-deploy
        run: make terraform-destroy
        working-directory: services/miyazaki/code-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - name: Destroy terraform miyazaki infra-deploy
        run: make terraform-destroy
        working-directory: services/miyazaki/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          ENVIRONMENT: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          ANSIBLE_VAULT_PASSWORD_FILE: vault_env
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.MIYAZAKI_ANSIBLE_VAULT_PASSWORD }}
