name: delete-terraform-cloudsre-hello-world-app-play-resources
on:
  push:
    tags:
      - delete-cloudsre-hello-world-app-play-*
jobs:
  delete-terraform-cloudsre-hello-world-app-play-resources-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        # run: wget `echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip"`  && unzip *.zip && sudo mv terraform /usr/bin/terraform
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_TEST_VERSION"/terraform_"$TF_TEST_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_TEST_VERSION: ${{ secrets.TF_TEST_VERSION }}

      - name: Delete the cloudsre-hello-world-app ECS service code deploy
        run: sed -i -e "s/TF_TOKEN_MIYAZAKI/$TF_TOKEN_MIYAZAKI/g" *.tf &&  sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf && /usr/bin/terraform init -input=false && /usr/bin/terraform destroy -input=false -auto-approve
        working-directory: services/cloudsre-hello-world-app/code-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}

      - name: Destroy terraform cloudsre-hello-world-app infra-deploy
        run: sed -i -e "s/TF_TOKEN_MIYAZAKI/$TF_TOKEN_MIYAZAKI/g" *.tf && sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf && sed -i -e "s/DOCKERGITHUBTOKEN/$DOCKER_GITHUB_TOKEN/g" *.tf && /usr/bin/terraform init -input=false && /usr/bin/terraform destroy -input=false -auto-approve
        working-directory: services/cloudsre-hello-world-app/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKERGITHUBTOKEN }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
