name: discover-code-deploy-play

on:
  repository_dispatch:
    types: [deploy-code-in-play]

# below lines are used for testing, need to remove this once code deploy is stable 

# on:
#   push:
#     branches:
#       - DI-*
#     tags:
#       - discover-code-play-*
#     paths:
#       - 'services/discover/code-deploy/**'

jobs:
  discover-code-deploy-job-play:
    runs-on: ubuntu-latest
    env:
      APP_TAG: ${{ github.event.client_payload.sha }}
      NODE_ENV: "NIGHTLY"
      TF_WORKSPACE: play
      TF_VAR_TF_TOKEN_DISCOVER: ${{ secrets.TF_TOKEN_DISCOVER }}
      TF_VAR_TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: checkout monohooq repo
        uses: actions/checkout@master
        with:
          path: 'monohooq'

      - name: checkout discover repo
        uses: actions/checkout@master
        with:
          repository: HOOQTV/discover
          token: ${{ secrets.DISCOVER_GITHUB_PAT }}
          ref: ${{ github.event.client_payload.ref }}
          path: 'discover'

      - name: push image to our Private Hub
        run: make docker-push
        working-directory: monohooq/services/discover/code-deploy
        env:
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - name: checkout monohooq repo
        uses: actions/checkout@master

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'services/discover/code-deploy/'
          args: '-backend-config="token=${{ secrets.TF_TOKEN_DISCOVER }}" -backend-config="organization=Discover"' 

      - name: 'Set the APP_TAG'
        run: |
          sed -i -e "s/APP_TAG/${APP_TAG}/g" variables.tf
          sed -i -e "s/NODE_ENV_VALUE/${NODE_ENV}/g" files/task-definitions/*.json
        working-directory: services/discover/code-deploy/

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'services/discover/code-deploy/'

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'services/discover/code-deploy/'
      
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: 'services/discover/code-deploy/'
