name: dockerize-awsweeper-pipeline
on: 
  push:
    tags:
      - awsweeper-package-*
jobs:
   dockerize-awsweeper-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Login to our private repository
        run: docker login quay.io --username hooq+techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - name: Build awsweeper docker image
        run: docker build -t quay.io/hooq/awsweeper:0.4.0 . 
        working-directory: cloud_sre/aws/script_for_lambda/delete_play_resources
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}

      - name: Push image to our private repository
        run: docker push quay.io/hooq/awsweeper:0.4.0
