name: miyazaki-metricbeat-deploy-play
on:
  push:
    tags:
      - miyazaki-metricbeat-play-*

jobs:
  deploy-miyazaki-metricbeat-deploy-play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Add GitHub Sha as version to terraform
        run: export GITHUBSHA=`git rev-parse HEAD | cut -c1-7` && sed -i -e "s/GITHUBSHA/$GITHUBSHA/g" variables.tf
        working-directory: services/miyazaki/metrics-deploy/metricbeat/

      - name: Apply terraform miyazaki metricbeat config
        run: make terraform-apply
        working-directory: services/miyazaki/metrics-deploy/metricbeat/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
      # - name: create dashboards and visualizations
      #   run: make ansible-apply
      #   working-directory: services/miyazaki/metrics-deploy/metricbeat/
      #   env:
      #     ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      #     ENVIRONMENT: play
