name: miyazaki-infra-deploy-dev
on:
  pull_request:
      types: [closed]
      paths:
      - 'services/miyazaki/infra-deploy/*.tf'
      - '!services/miyazaki/infra-deploy/functionbeat.conf'
  push:
    tags:
      - MIYAZAKI-DEV-INFRA-*
jobs:
  miyazaki-infra-development-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@v1.2.0

      - name: Install botocore and boto3
        run: pip install botocore boto3

      - name: Get the latest terraform version
        run: make terraform-install
        
      - name: Set elasticache password
        run:  sed -i -e "s/MIYAZAKI_REDIS_PASSWORD/$MIYAZAKI_DEV_REDIS_PASSWORD/g" redis.tf
        working-directory: services/miyazaki/infra-deploy/
        env:
          MIYAZAKI_DEV_REDIS_PASSWORD: ${{ secrets.MIYAZAKI_DEV_REDIS_PASSWORD }}

      - name: Apply terraform miyazki infra
        run: make terraform-apply
        working-directory: services/miyazaki/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKERGITHUBTOKEN }}
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          ANSIBLE_VAULT_PASSWORD_FILE: vault_env
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.MIYAZAKI_ANSIBLE_VAULT_PASSWORD }}
          AWS_ACCEPTER_ACCESS_KEY: ${{ secrets.AWS_CC_PROD_ACCESS_KEY }}
          AWS_ACCEPTER_SECRET_KEY: ${{ secrets.AWS_CC_PROD_SECRET_KEY }}
          AWS_INITIATOR_ACCESS_KEY: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_INITIATOR_SECRET_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          ENVIRONMENT: dev

      - name: code promotion DEV to STAG to PROD
        if: github.event.pull_request.merged == true
        run:  |
          export PULL_REQUEST_COMMIT_ID_SHORT=`sed -e 's/^"//' -e 's/"$//' <<<"$MASTER_COMMIT_ID" | cut -c1-7`
          echo "Commit id short is:  $PULL_REQUEST_COMMIT_ID_SHORT"
          export PULL_REQUEST_COMMIT_ID_FULL=`sed -e 's/^"//' -e 's/"$//' <<<"$MASTER_COMMIT_ID"`
          echo "Commit id full is: $PULL_REQUEST_COMMIT_ID_FULL"
          echo "git fetch origin master"
          echo "------------------------------------------------DEV->STAG-----------------------------------------------------------------------------------------------------------------------------"
          echo "Command to promote infra for STAG is:   git tag -a MIYAZAKI-STAG-INFRA-$PULL_REQUEST_COMMIT_ID_SHORT $PULL_REQUEST_COMMIT_ID_FULL -m \"Infra Promotion from the DEV to STAG\""
          echo "Command to push stage tags:  git push origin MIYAZAKI-STAG-INFRA-$PULL_REQUEST_COMMIT_ID_SHORT"
          echo "------------------------------------------------STAG->PROD-----------------------------------------------------------------------------------------------------------------------------"
          echo "Command to promote infra for PROD is:   git tag -a MIYAZAKI-PROD-INFRA-$PULL_REQUEST_COMMIT_ID_SHORT $PULL_REQUEST_COMMIT_ID_FULL -m \"Infra Promotion from the STAG to PROD\""
          echo "Command to push Prod tags:  git push origin MIYAZAKI-PROD-INFRA-$PULL_REQUEST_COMMIT_ID_SHORT"
        working-directory: services/miyazaki/infra-deploy/
        env:
          MASTER_COMMIT_ID: ${{ toJson(github.event.pull_request.merge_commit_sha) }}
