name: miyazaki-code-deploy-dev
on:
  push:
    branches:
      - PW-*
      - GRB-*
      - CS-*
    tags:
      - MIYAZAKI-DEV-CODE-*
    paths:
      - "services/miyazaki/code-deploy/**"
      - ".github/workflows/miyazaki-code-deploy-dev.yml"

jobs:
  miyazaki-client-side-test-job-dev:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:5
        ports:
          - 6379:6379
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.TECHACC_TOKEN}}

      - name: git merge origin master
        run: make git-merge-master
        env:
          GITHUB_REF: ${{ toJson(github.ref) }}

      - name: install dependencies and run test
        run: |
          make yarn-install yarn-test-client yarn-test-common yarn-test-server
        working-directory: services/miyazaki/code-deploy/src
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}

  miyazaki-image-build-job-dev:
    runs-on: ubuntu-latest
    needs: miyazaki-client-side-test-job-dev

    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: build and push docker image to private hub
        run: |
          export APP_TAG=${GITHUB_REF##*/}
          make docker-push
        env:
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}
          DOCKER_FILE_PATH : services/miyazaki/code-deploy/src
          DOCKER_HOST 		: quay.io
          DOCKER_IMAGE 		: quay.io/hooq/miyazaki
          DOCKER_USERNAME	: hooq+techacc
          GITHUB_REF: ${{ toJson(github.ref) }}
          QUAY_ACCESS_TOKEN: ${{ secrets.QUAY_ACCESS_TOKEN }}
          SERVICE_NAME : miyazaki

  miyazaki-ecs-deployment-dev:
    runs-on: ubuntu-latest
    needs: miyazaki-image-build-job-dev
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: make terraform-install

      - name: apply terraform
        run: |
          export APP_TAG=${GITHUB_REF##*/} && sed -i -e "s/APP_TAG/$APP_TAG/g" *.tf
          make terraform-apply
        working-directory: services/miyazaki/code-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
