name: miyazaki-infra-deploy-stag
on:
  push:
    tags:
      - MIYAZAKI-STAG-INFRA-*

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@v1.2.0

      - name: Install botocore and boto3
        run: pip install botocore boto3

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Set elasticache password
        run:  sed -i -e "s/MIYAZAKI_REDIS_PASSWORD/$MIYAZAKI_STAG_REDIS_PASSWORD/g" redis.tf
        working-directory: services/miyazaki/infra-deploy/
        env:
          MIYAZAKI_STAG_REDIS_PASSWORD: ${{ secrets.MIYAZAKI_STAG_REDIS_PASSWORD }}

      - name: Apply terraform miyazki infra
        run: make terraform-apply
        working-directory: services/miyazaki/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKERGITHUBTOKEN }}
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          ANSIBLE_VAULT_PASSWORD_FILE: vault_env
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.MIYAZAKI_ANSIBLE_VAULT_PASSWORD }}
          AWS_ACCEPTER_ACCESS_KEY: ${{ secrets.AWS_CC_PROD_ACCESS_KEY }}
          AWS_ACCEPTER_SECRET_KEY: ${{ secrets.AWS_CC_PROD_SECRET_KEY }}
          AWS_INITIATOR_ACCESS_KEY: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_INITIATOR_SECRET_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          ENVIRONMENT: stag
