name: miyazaki-config-dev-pipeline
on:
  push:
    tags:
      - miyazaki-config-dev-*
    branches:
      - master
    paths:
      - "services/miyazaki/config-deploy/**"

jobs:
  miyazaki-config-dev-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Install botocore and boto3
        run: pip install botocore boto3

      - name: Get the latest terraform version
        run: make terraform-install
        

      - name: Apply terraform miyazaki config
        run: make terraform-apply
        working-directory: services/miyazaki/config-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}

      - name: Configs for miyazaki secrets
        run: make ansible-apply
        working-directory: services/miyazaki/config-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: vault_env
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.MIYAZAKI_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
