name: miyazaki-code-deploy-prod
on:
  push:
    tags:
      - MIYAZAKI-PROD-CODE-*

jobs:
  miyazaki-image-build-job-prod:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: validate commit_id with head_commit_sha
        run: |
          BRANCH_TAG=`printf $(cut -d- -f4 <<< $GITHUB_REF)`
          export INPUT_COMMIT_SHA=$(git rev-parse $BRANCH_TAG)
          make validate-commit-sha
        env:
          GITHUB_REF: ${{ toJson(github.ref) }}
          GITHUB_HEAD_COMMIT_SHA: ${{ toJson(github.event.head_commit.id) }}

      - name: pull docker image tested in staging
        run: |
          export BRANCH_TAG=`printf $(cut -d- -f4 <<< $GITHUB_REF)`
          make docker-pull
        env:
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          DOCKER_HOST 		: quay.io
          DOCKER_IMAGE 		: quay.io/hooq/miyazaki
          DOCKER_USERNAME	: hooq+techacc
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}
          GITHUB_REF: ${{ toJson(github.ref) }}


  miyazaki-ecs-deployment-prod:
    runs-on: ubuntu-latest
    needs: miyazaki-image-build-job-prod
    steps:
      - name: checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: make terraform-install

      - name: apply terraform
        run: |
          export APP_TAG=`printf $(cut -d- -f4 <<< $GITHUB_REF)` && sed -i -e "s/APP_TAG/$APP_TAG/g" *.tf
          make terraform-apply
        working-directory: services/miyazaki/code-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: prod
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
          GITHUB_REF: ${{ toJson(github.ref) }}
