name: delete-terraform-nikita-dev-resources
on:
  push:
    tags:
      - delete-nikita-dev-*
jobs:
  delete-code-api-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy terraform api
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/code-deploy/api/terraform/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  delete-code-portal-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy terraform portal
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/code-deploy/portal/terraform/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  delete-code-lambda-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: destroy lambdas
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/code-deploy/lambda
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  delete-code-db-migration-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy db-migration
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/code-deploy/db_migration
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_db_migration_command: mix ecto.migrate
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  delete-api-rule-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy terraform kong api rules
        run: make terraform-install terraform-install-kong-plugin terraform-destroy
        working-directory: services/nikita/api-rule-deploy
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_kong_admin_uri: https://nikita-kong-admin.dev-hooq.tv
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: dev

  delete-code-kong-admin-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy terraform kong admin
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/code-deploy/kong/terraform-admin/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  delete-code-kong-main-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy terraform kong main
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/code-deploy/kong/terraform-main/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  delete-infra-dev:
    runs-on: ubuntu-latest
    needs:
      - delete-code-api-dev
      - delete-code-portal-dev
      - delete-code-lambda-dev
      - delete-code-db-migration-dev
      - delete-code-kong-admin-dev
      - delete-code-kong-main-dev
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Destroy nikita infra-deploy
        run: make terraform-install terraform-destroy
        working-directory: services/nikita/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: dev
