name: nikita-code-deploy-portal-stag
on:
  push:
    branches:
      - master
    tags:
      - nikita-portal-stag-*
    paths:
      - 'services/nikita/code-deploy/portal/**'

jobs:
  nikita-code-deploy-portal-ecs-stag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: apply terraform
        run: make docker-push terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/portal
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
