name: nikita-code-deploy-api-prod
on:
  push:
    tags:
      - nikita-api-prod-*

jobs:
  nikita-code-deploy-api-ecs-prod:
    runs-on: ubuntu-latest
    needs: nikita-code-deploy-api-image-prod
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: apply terraform
        run: make git-setup terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/api
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: prod
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}
