name: nikita-code-deploy-kong-dev
on:
  push:
    tags:
      - nikita-kong-dev-*
    branches:
      - UM-*
    paths:
      - 'services/nikita/code-deploy/kong/**'

jobs:
  nikita-code-deploy-kong-merge-master-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.TECHACC_TOKEN}}

      - name: git merge origin master
        run: make git-merge-master
        env:
          GITHUB_REF: ${{ toJson(github.ref) }}

  nikita-code-deploy-kong-migration-dev:
    runs-on: ubuntu-latest
    needs: nikita-code-deploy-kong-merge-master-dev
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: apply terraform with migrate command
        run: make terraform-install terraform-taint-task-runner terraform-apply
        working-directory: services/nikita/code-deploy/kong/terraform-migration/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_db_migration_command: kong migrations bootstrap && kong migrations up && kong migrations finish
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}

  nikita-code-deploy-kong-admin-dev:
    runs-on: ubuntu-latest
    needs: nikita-code-deploy-kong-migration-dev
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: apply terraform
        run: make terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/kong/terraform-admin/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

  nikita-code-deploy-kong-main-dev:
    runs-on: ubuntu-latest
    needs: nikita-code-deploy-kong-admin-dev
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: apply terraform
        run: make terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/kong/terraform-main/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
