name: nikita-code-deploy-db-migration-stag
on:
  push:
    tags:
      - nikita-db-migrate-stag-*
      - nikita-db-rollback-stag-*
    branches:
      - master
    paths:
      - 'services/nikita/code-deploy/db_migration/**'

jobs:
  nikita-code-deploy-db-migration-run-stag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/nikita-db-migrate-stag-')
        name: apply terraform with migrate command
        run: make docker-push terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/db_migration/terraform/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_db_migration_command: mix ecto.migrate
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_STAG_SECRET_KEY }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/nikita-db-rollback-stag-')
        name: apply terraform with rollback command
        run: make docker-push terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/db_migration/terraform/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_db_migration_command: mix ecto.rollback
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_STAG_SECRET_KEY }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
