name: nikita-code-deploy-db-migration-dev
on:
  push:
    tags:
      - nikita-db-migrate-dev-*
      - nikita-db-rollback-dev-*
    branches:
      - UM-*
    paths:
      - 'services/nikita/code-deploy/db_migration/**'

jobs:
  nikita-code-deploy-db-migration-merge-master-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.TECHACC_TOKEN}}

      - name: git merge origin master
        run: make git-merge-master
        env:
          GITHUB_REF: ${{ toJson(github.ref) }}

  nikita-code-deploy-db-migration-run-dev:
    runs-on: ubuntu-latest
    needs: nikita-code-deploy-db-migration-merge-master-dev
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - if: startsWith(github.ref, 'refs/tags/nikita-db-migrate-dev-') || startsWith(github.ref, 'refs/heads/UM-')
        name: apply terraform with migrate command
        run: make docker-push terraform-install terraform-taint-task-runner terraform-apply
        working-directory: services/nikita/code-deploy/db_migration
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_db_migration_command: mix ecto.migrate
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/nikita-db-rollback-dev-')
        name: apply terraform with rollback command
        run: make docker-push terraform-install terraform-taint-task-runner terraform-apply
        working-directory: services/nikita/code-deploy/db_migration
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          TF_VAR_db_migration_command: mix ecto.rollback
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_DEV_SECRET_KEY }}
          DOCKER_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
