name: nikita-config-deploy
on:
  push:
    tags:
      - nikita-config-play-*
      - nikita-config-dev-*
      - nikita-config-stag-*
      - nikita-config-prod-*
    branches:
      - UM-*
      - master
    paths:
      - 'services/nikita/config-deploy/**'

jobs:
  nikita-config-deploy-play:
    if: startsWith(github.ref, 'refs/tags/nikita-config-play-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Apply terraform nikita config
        run: make terraform-install terraform-apply
        working-directory: services/nikita/config-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}

      - name: Configs for nikita secrets
        run: make ansible-apply
        working-directory: services/nikita/config-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  nikita-config-deploy-dev:
    if: startsWith(github.ref, 'refs/tags/nikita-config-dev-') || startsWith(github.ref, 'refs/heads/UM-')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Apply terraform nikita config
        run: make terraform-install terraform-apply
        working-directory: services/nikita/config-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}

      - name: Configs for nikita secrets
        run: make ansible-apply
        working-directory: services/nikita/config-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  nikita-config-deploy-stag:
    if: startsWith(github.ref, 'refs/tags/nikita-config-stag-') || startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Apply terraform nikita config
        run: make terraform-install terraform-apply
        working-directory: services/nikita/config-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: stag
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}

      - name: Configs for nikita secrets
        run: make ansible-apply
        working-directory: services/nikita/config-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: stag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAG_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  nikita-config-deploy-prod:
    if: startsWith(github.ref, 'refs/tags/nikita-config-prod-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Apply terraform nikita config
        run: make terraform-install terraform-apply
        working-directory: services/nikita/config-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: prod
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}

      - name: Configs for nikita secrets
        run: make ansible-apply
        working-directory: services/nikita/config-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.NIKITA_ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
