name: nikita-code-deploy-lambda-dev
on:
  push:
    tags:
      - nikita-lambda-dev-auto-*
      - nikita-lambda-dev-all-*
      - nikita-lambda-dev-account-stream-consumer-*
      - nikita-lambda-dev-account-stream-producer-*
      - nikita-lambda-dev-transaction-stream-consumer-*
      - nikita-lambda-dev-transaction-stream-producer-*
    branches:
      - UM-*
    paths:
      - "services/nikita/code-deploy/lambda/**/*.go"
      - "services/nikita/code-deploy/lambda/**/*.tf"
      - "services/nikita/code-deploy/lambda/**/Makefile"

jobs:
  nikita-code-deploy-lambda-auto-dev:
    if: startsWith(github.ref, 'refs/heads/UM-') || startsWith(github.ref, 'refs/tags/nikita-lambda-dev-auto-')
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build and update lambdas
        run: make git-setup auto-build terraform-install auto-terraform-apply
        working-directory: services/nikita/code-deploy/lambda
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}

  nikita-code-deploy-lambda-all-dev:
    if: startsWith(github.ref, 'refs/tags/nikita-lambda-dev-all-')
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: build and update lambdas
        run: make git-setup build terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/lambda
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}

  nikita-code-deploy-lambda-account-stream-consumer-dev:
    if: startsWith(github.ref, 'refs/tags/nikita-lambda-dev-account-stream-consumer-')
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: build and update account_stream_consumer
        run: make git-setup build terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/lambda/account_stream_consumer
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}

  nikita-code-deploy-lambda-account-stream-producer-dev:
    if: startsWith(github.ref, 'refs/tags/nikita-lambda-dev-account-stream-producer-')
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: build and update account_stream_producer
        run: make git-setup build terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/lambda/account_stream_producer
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}

  nikita-code-deploy-lambda-transaction-stream-consumer-dev:
    if: startsWith(github.ref, 'refs/tags/nikita-lambda-dev-transaction-stream-consumer-')
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: build and update transaction_stream_consumer
        run: make git-setup build terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/lambda/transaction_stream_consumer
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}

  nikita-code-deploy-lambda-transaction-stream-producer-dev:
    if: startsWith(github.ref, 'refs/tags/nikita-lambda-dev-transaction-stream-producer-')
    runs-on: ubuntu-latest
    steps:
      - name: checkout public repo
        uses: actions/checkout@v2

      - name: build and update transaction_stream_producer
        run: make git-setup build terraform-install terraform-apply
        working-directory: services/nikita/code-deploy/lambda/transaction_stream_producer
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: dev
          TF_TOKEN_NIKITA: ${{ secrets.TF_TOKEN_NIKITA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
          SSH_KEY: ${{ secrets.DEPLOYER_KEY_PRIV }}
          SSH_KEY_PUB: ${{ secrets.DEPLOYER_KEY_PUB }}
