name: scheduler-terraform-cloudsre-helloworld-app-play-delete-action
on:
 schedule:
   # The cron will run at 7:00 PM at UTC, 3:00 AM at SGT, and 2:00 AM at Jakarta Time
   - cron:  '0 19 * * *'


jobs:
  destroy-terraform-cloudsre-helloworld-app-play-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Login to our private repository
        run: docker login docker.pkg.github.com --username HOOQTV -p $TOKEN
        env:
          TOKEN: ${{ secrets.TECHACC_TOKEN }}

      - name: Get the latest terraform version
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_TEST_VERSION"/terraform_"$TF_TEST_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_TEST_VERSION: ${{ secrets.TF_TEST_VERSION }}

      - name: Destroy terraform cloudsre helloworld infra-deploy
        run: sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf && /usr/bin/terraform init -input=false && /usr/bin/terraform destroy -input=false  -auto-approve
        working-directory: services/cloudsre-hello-world-app/code-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}

      - name: Destroy terraform cloudsre helloworld infra-deploy
        run: sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf && /usr/bin/terraform init -input=false && /usr/bin/terraform destroy -input=false  -auto-approve
        working-directory: services/cloudsre-hello-world-app/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}