name: scheduler-terraform-miyazaki-play-delete-action
on: 
 schedule:
   # The cron will run at 7:00 PM at UTC, 3:00 AM at SGT, and 2:00 AM at Jakarta Time
   - cron:  '0 19 * * *'


jobs:
  destroy-terraform-miyazaki-play-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Login to our private repository
        run: docker login quay.io --username hooq+techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}

      - name: Get the latest terraform version
        run: curl -L -O https://releases.hashicorp.com/terraform/"$TF_TEST_VERSION"/terraform_"$TF_TEST_VERSION"_linux_amd64.zip && unzip *.zip && sudo mv terraform /usr/bin/terraform
        env:
          TF_TEST_VERSION: ${{ secrets.TF_TEST_VERSION }}


      - name: Destroy terraform miyazaki infra-deploy
        run: | 
          sed -i -e "s/TF_TOKEN_MIYAZAKI/$TF_TOKEN_MIYAZAKI/g" *.tf 
          sed -i -e "s/TF_TOKEN_CLOUD_SRE/$TF_TOKEN_CLOUD_SRE/g" *.tf
          sed -i -e "s@AWS_INITIATOR_ACCESS_KEY@$AWS_INITIATOR_ACCESS_KEY@g;s@AWS_INITIATOR_SECRET_KEY@$AWS_INITIATOR_SECRET_KEY@g;s@AWS_ACCEPTER_SECRET_KEY@$AWS_ACCEPTER_SECRET_KEY@g;s@AWS_ACCEPTER_ACCESS_KEY@$AWS_ACCEPTER_ACCESS_KEY@g" vpc_peering.tf 
          sed -i -e "s/PRIVATE_REGISTRY_TOKEN/$PRIVATE_REGISTRY_TOKEN/g" application_infra.tf
          /usr/bin/terraform init -input=false 
          /usr/bin/terraform destroy -input=false -auto-approve
        working-directory: services/miyazaki/infra-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}
          TF_TOKEN_MIYAZAKI: ${{ secrets.TF_TOKEN_MIYAZAKI }}
          TF_TOKEN_CLOUD_SRE: ${{ secrets.TF_TOKEN_CLOUD_SRE }}
          AWS_ACCEPTER_ACCESS_KEY: ${{ secrets.AWS_CC_PROD_ACCESS_KEY }}
          AWS_ACCEPTER_SECRET_KEY: ${{ secrets.AWS_CC_PROD_SECRET_KEY }}
          AWS_INITIATOR_ACCESS_KEY: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_INITIATOR_SECRET_KEY: ${{ secrets.AWS_PLAY_SECRET_KEY }}
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}


      - name: Run docker for delete resources
        run:  docker run --rm -i -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" -e "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" quay.io/hooq/awsweeper:0.4.0
        env:
          TOKEN: ${{ secrets.TOKEN }}
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PLAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_PLAY_SECRET_KEY }}
